name = "Minimus"
license = "UNLICENSE"
licenselink = ""
description = "theme for nomasters.io"
homepage = "https://nomasters.io"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive"
]
features = []
min_version = 0.28

[author]
  name = "n2p5"
  homepage = "https://nomasters.io"
