version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.22
  hugo: circleci/hugo@0.4.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    executor: aws-cli/default
    working_directory: ~/repo
    steps:
      - aws-cli/install
      - checkout
      - attach_workspace:
          at: site
      - run: scripts/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - hugo/build:
          source: site/
          html-proofer: false
      - deploy:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - hugo/build
